import React from 'react';
import { AlertTriangle, ShieldCheck } from 'lucide-react';

const LegalDisclaimer: React.FC = () => {
  return (
    <div className="max-w-3xl mx-auto space-y-6 animate-fade-in relative z-10">
      
      {/* Disclaimer Card */}
      <div className="bg-white dark:bg-gray-900 border border-gray-200/60 dark:border-gray-800/60 rounded-3xl p-6 md:p-8 shadow-sm space-y-6">
        
        {/* Title */}
        <div className="flex items-center space-x-3.5 pb-4 border-b border-gray-150 dark:border-gray-800">
          <div className="p-3 bg-amber-500/10 text-amber-500 rounded-2xl">
            <AlertTriangle size={24} />
          </div>
          <div>
            <h1 className="text-xl font-bold tracking-tight text-gray-900 dark:text-white">Legal Disclaimer & Compliance</h1>
            <p className="text-xs text-gray-400">Please read carefully before using the advisory tools.</p>
          </div>
        </div>

        {/* Disclaimer Body */}
        <div className="space-y-4 text-xs text-gray-500 dark:text-gray-400 leading-relaxed font-sans">
          
          <h3 className="font-bold text-gray-800 dark:text-gray-200 uppercase tracking-wider text-[10px]">
            1. Nature of the Service
          </h3>
          <p>
            The information, content, analysis, draft clauses, and citations generated by **Nyaya AI** (collectively, the "Platform") are intended for **informational, educational, and workflow assistance purposes only**. The Platform utilizes mock and automated inference systems to reference standard Indian statutes (including BNS, BNSS, BSA, IPC, CrPC, and local civil acts) but does not guarantee the accuracy, completeness, or up-to-date status of any legal content.
          </p>

          <h3 className="font-bold text-gray-800 dark:text-gray-200 uppercase tracking-wider text-[10px]">
            2. No Lawyer-Client Relationship
          </h3>
          <p>
            Use of this Platform, transmission of queries, and document uploads do not create an advocate-client relationship between the user and the Platform or any associated entities. The outputs generated by the AI should not be construed as formal legal opinion, professional advocacy, or a substitute for expert legal consultation.
          </p>

          <h3 className="font-bold text-gray-800 dark:text-gray-200 uppercase tracking-wider text-[10px]">
            3. Bar Council of India (BCI) Compliance
          </h3>
          <p>
            In accordance with the rules of the **Bar Council of India (BCI)**, advocates are prohibited from soliciting work or advertising their services. This Platform is a tool for legal practitioners to streamline case management and legal research. It does not advertise, solicit, or invite clients on behalf of any specific advocate. Users are encouraged to exercise independent professional judgment when referencing any output in court petitions or litigation filings.
          </p>

          <h3 className="font-bold text-gray-800 dark:text-gray-200 uppercase tracking-wider text-[10px]">
            4. Limitation of Liability
          </h3>
          <p>
            The Platform, its developers, and contributors shall not be held liable for any loss, damage, or legal penalty arising from reliance on the automated advice, draft clauses, or citations provided herein. Users are advised to cross-reference citations with the official gazettes of the Legislative Department, Government of India, and verified law reporters.
          </p>

        </div>

        {/* Verification Checkmark Banner */}
        <div className="p-4 bg-gray-50 dark:bg-gray-950 border border-gray-200 dark:border-gray-850 rounded-2xl flex items-start space-x-3">
          <ShieldCheck size={18} className="text-emerald-500 shrink-0 mt-0.5" />
          <div className="space-y-1">
            <h4 className="text-xs font-bold text-gray-900 dark:text-white">Compliance Acknowledgment</h4>
            <p className="text-[10px] text-gray-400 leading-normal">
              By accessing the dashboards and launching case consultations, you acknowledge and agree that you are a legal practitioner or researcher accessing these resources voluntarily for reference purposes.
            </p>
          </div>
        </div>

      </div>

    </div>
  );
};

export default LegalDisclaimer;
